/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ABB_Arbol_Binario;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/**
 *
 * @author rszaldumbide
 */


public class VistaArboles extends javax.swing.JFrame {

    /**
     * Creates new form VistaArboles
     */

    private arbolBinario_ABB ABB;
    private ABB_metodo_reflexivo ABB2;
    Graphics arbol, arbol2;
    int x, y, x2, y2;
    public VistaArboles() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        this.ABB = new arbolBinario_ABB();
        this.ABB2= new ABB_metodo_reflexivo();
        arbol = this.pnlGrafico.getGraphics();
        x = pnlGrafico.getWidth() / 2;
        y = pnlGrafico.getHeight() / 5;
        x2 = pnlGrafico.getWidth() / 10;
        y2 = pnlGrafico.getHeight() / 10;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnGraficar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlGrafico = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        btnGenerarRandom = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnAltura = new javax.swing.JButton();
        btnContarNodos = new javax.swing.JButton();
        btnNodosPrimos = new javax.swing.JButton();
        btnNodosHojas = new javax.swing.JButton();
        btnPreOrden = new javax.swing.JButton();
        btnInOrden = new javax.swing.JButton();
        btnPosOrden = new javax.swing.JButton();
        btnPeso = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCamino = new javax.swing.JButton();
        pnl2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        pnlDatos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText("Dato:");

        btnGraficar.setBackground(new java.awt.Color(0, 0, 0));
        btnGraficar.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnGraficar.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Grafica manualmente cada elemento ");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ingresado en la casilla Dato");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDato))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnGraficar))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGraficar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pnlGrafico.setBackground(new java.awt.Color(255, 255, 255));
        pnlGrafico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Arbol 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 3, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1023, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnGenerarRandom.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerarRandom.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarRandom.setText("GenerarRandom");
        btnGenerarRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarRandomActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAltura.setBackground(new java.awt.Color(0, 0, 0));
        btnAltura.setForeground(new java.awt.Color(255, 255, 255));
        btnAltura.setText("Altura");
        btnAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlturaActionPerformed(evt);
            }
        });

        btnContarNodos.setBackground(new java.awt.Color(0, 0, 0));
        btnContarNodos.setForeground(new java.awt.Color(255, 255, 255));
        btnContarNodos.setText("Contar Nodos");
        btnContarNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarNodosActionPerformed(evt);
            }
        });

        btnNodosPrimos.setBackground(new java.awt.Color(0, 0, 0));
        btnNodosPrimos.setForeground(new java.awt.Color(255, 255, 255));
        btnNodosPrimos.setText("Nodos Primos");
        btnNodosPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNodosPrimosActionPerformed(evt);
            }
        });

        btnNodosHojas.setBackground(new java.awt.Color(0, 0, 0));
        btnNodosHojas.setForeground(new java.awt.Color(255, 255, 255));
        btnNodosHojas.setText("Nodos Hojas");
        btnNodosHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNodosHojasActionPerformed(evt);
            }
        });

        btnPreOrden.setBackground(new java.awt.Color(0, 0, 0));
        btnPreOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnPreOrden.setText("PreOrden");
        btnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrdenActionPerformed(evt);
            }
        });

        btnInOrden.setBackground(new java.awt.Color(0, 0, 0));
        btnInOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnInOrden.setText("InOrden");
        btnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrdenActionPerformed(evt);
            }
        });

        btnPosOrden.setBackground(new java.awt.Color(0, 0, 0));
        btnPosOrden.setForeground(new java.awt.Color(255, 255, 255));
        btnPosOrden.setText("PosOrden");
        btnPosOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosOrdenActionPerformed(evt);
            }
        });

        btnPeso.setBackground(new java.awt.Color(0, 0, 0));
        btnPeso.setForeground(new java.awt.Color(255, 255, 255));
        btnPeso.setText("Peso");
        btnPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoActionPerformed(evt);
            }
        });

        btnGenerar.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Genera Arbol predefinido");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 9)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Genera un arbol de tamaño ingresado");

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setText("Dato:");

        btnCamino.setBackground(new java.awt.Color(0, 0, 0));
        btnCamino.setForeground(new java.awt.Color(255, 255, 255));
        btnCamino.setText("Camino mas corto:");
        btnCamino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnContarNodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAltura)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPreOrden)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPosOrden)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNodosPrimos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNodosHojas)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGenerarRandom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGenerar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(btnCamino))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(jLabel1))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarRandom)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAltura)
                    .addComponent(btnContarNodos))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNodosPrimos)
                    .addComponent(btnNodosHojas))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInOrden)
                    .addComponent(btnPosOrden))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPeso)
                    .addComponent(btnPreOrden))
                .addGap(18, 18, 18)
                .addComponent(btnCamino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl2.setBackground(new java.awt.Color(255, 255, 255));
        pnl2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Arbol 2: Reflejo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 3, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        try{    
            ABB = new arbolBinario_ABB();
            ABB2= new ABB_metodo_reflexivo();
            int dato=Integer.parseInt(txtDato.getText());
            ABB.insertar(dato);
          
            Graphics arbol= this.pnlGrafico.getGraphics();
            
            graficarArbol(arbol, ABB.getRaiz(), x/2, 10, 50, 50, 1);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        txtDato.setText("");
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            int datoBuscar=Integer.parseInt(txtCantidad.getText());
            nodo encontrado=ABB.Buscar2(datoBuscar);
            if(encontrado!=null){
                JOptionPane.showMessageDialog(null, "Dato encontrado");
            }else{
                JOptionPane.showMessageDialog(null, "No existe el nodo");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGenerarRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarRandomActionPerformed
        // TODO add your handling code here:
        try {
            ABB = new arbolBinario_ABB();
            ABB2= new ABB_metodo_reflexivo();
            arbol = this.pnlGrafico.getGraphics();
            arbol2 = this.pnl2.getGraphics();

            int cantidad = Integer.parseInt(txtCantidad.getText());
            int numero;
            for (int i = 0; i < cantidad; i++) {
                //genera nums aleatorios desde el -10 al 20
                numero = (int) (Math.random() * 99 + 50);
                ABB.insertar(numero);
                ABB2.insertarReflexivo(numero);
            }
            graficarArbol(arbol, ABB.getRaiz(), x, y, x2, y2, 1);
            graficarArbol(arbol2, ABB2.getRaiz(), x, y, x2, y2, 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnGenerarRandomActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        //<editor-fold defaultstate="collapsed" desc="comment/*comment*/">
        this.pnlGrafico.repaint();
//</editor-fold>this.pnlGrafico.repaint();
        this.pnl2.repaint();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlturaActionPerformed
        // TODO add your handling code here:
        String altura=ABB.altura();
        String altura2=ABB2.altura();
        JOptionPane.showMessageDialog(null, altura+altura2);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnAlturaActionPerformed

    private void btnContarNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarNodosActionPerformed
        // TODO add your handling code here:
        String cantNodos=ABB.Nodos();
        String cantNodos2=ABB2.Nodos();
        JOptionPane.showMessageDialog(null, cantNodos+cantNodos2);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnContarNodosActionPerformed

    private void btnNodosHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNodosHojasActionPerformed
        // TODO add your handling code here:
        String hojas=ABB.nodosHojas();
        String hojas2= ABB2.nodosHojas();
        JOptionPane.showMessageDialog(null, hojas+hojas2);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnNodosHojasActionPerformed

    private void btnNodosPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNodosPrimosActionPerformed
        // TODO add your handling code here:
        String primos=ABB.nodosPrimos();
        String primos2=ABB2.nodosPrimos();
        JOptionPane.showMessageDialog(null, "Arbol 1: Los nodos que contienen numeros primos son: "+primos
        +"Arbol 2 Reflexivo: Los nodos que contienen numeros primos son: "+primos2);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnNodosPrimosActionPerformed

    private void btnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrdenActionPerformed
        // TODO add your handling code here:
        String preorden=ABB.preOrden();
        String preOrdenRef=ABB2.preOrden();
        JOptionPane.showMessageDialog(null, "El recorrido en PreOrden del Arbol 1 es: "+preorden
        +"\n El recorrido en PreOrden del Arbol 2 Reflexivo es: "+preOrdenRef);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnPreOrdenActionPerformed

    private void btnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrdenActionPerformed
        // TODO add your handling code here:
        String inorden=ABB.InOrden();
        String inOrdenRef=ABB2.InOrden2();
        JOptionPane.showMessageDialog(null, "El recorrido en InOrden es: "+inorden
        +"\n El recorrido en InOrden del Arbol 2 Reflexivo es: "+inOrdenRef);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnInOrdenActionPerformed

    private void btnPosOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosOrdenActionPerformed
        // TODO add your handling code here:
        String postorden=ABB.PosOrden();
        String postordenRef=ABB2.PosOrden();
        JOptionPane.showMessageDialog(null, "El recorrido en PostOrden es: "+postorden
        +"\n El recorrido en PosOrden del Arbol 2 Reflexivo es: "+postordenRef);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnPosOrdenActionPerformed

    private void btnPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoActionPerformed
        // TODO add your handling code here:
        String peso=ABB.ramaPeso();
        String peso2=ABB2.ramaPeso2();
        JOptionPane.showMessageDialog(null, "Arbol 1: \n"+peso+"\nArbol 2:\n"+peso2);
        txtCantidad.setText("");
    }//GEN-LAST:event_btnPesoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        try {
            ABB = new arbolBinario_ABB();
            ABB2= new ABB_metodo_reflexivo();
            arbol = this.pnlGrafico.getGraphics();
            arbol2 = this.pnl2.getGraphics();
                //se insertan elementos
                ABB.insertar(12);
                ABB.insertar(6);
                ABB.insertar(2);
                ABB.insertar(32);
                ABB.insertar(-10);
                ABB.insertar(108);
                ABB2.insertarReflexivo(12);
                ABB2.insertarReflexivo(6);
                ABB2.insertarReflexivo(2);
                ABB2.insertarReflexivo(32);
                ABB2.insertarReflexivo(-10);
                ABB2.insertarReflexivo(108);
            
            graficarArbol(arbol, ABB.getRaiz(), x, y, x2, y2, 1);
            graficarArbol(arbol2, ABB2.getRaiz(), x, y, x2, y2, 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCaminoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminoActionPerformed
        // TODO add your handling code here:
        try{
            int datoBuscar=Integer.parseInt(txtCantidad.getText());
            String camino=ABB.caminoCorto(datoBuscar);
            JOptionPane.showMessageDialog(null, camino);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txtCantidad.setText("");
    }//GEN-LAST:event_btnCaminoActionPerformed

    private void graficarArbol(Graphics arbol, nodo raiz, int x, int y, int auxX, int auxY, int nivel){
        
        if (raiz!= null) {
            //graficando las lineas
            arbol.setColor(Color.BLACK);
            if (raiz.izq != null) {
                arbol.drawLine(x, y, x - auxX + (nivel * 2), y + auxY);
            }
            if (raiz.der != null) {
                arbol.drawLine(x, y, x + auxX - (nivel * 2), y + auxY);
            }
            //graficando
            arbol.setColor(Color.YELLOW);
            arbol.fillOval(x - 10, y - 20, 40, 40);
            arbol.setColor(Color.BLACK);
            arbol.drawString(String.valueOf(raiz.info), x, y);

            //recursividad
            graficarArbol(arbol, raiz.izq, x - auxX, y + auxY, auxX + nivel * 2, auxY * 2, nivel + 2);
            graficarArbol(arbol, raiz.der, x + auxX, y + auxY, auxX - nivel * 2, auxY, nivel + 1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaArboles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaArboles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltura;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCamino;
    private javax.swing.JButton btnContarNodos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGenerarRandom;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnInOrden;
    private javax.swing.JButton btnNodosHojas;
    private javax.swing.JButton btnNodosPrimos;
    private javax.swing.JButton btnPeso;
    private javax.swing.JButton btnPosOrden;
    private javax.swing.JButton btnPreOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlGrafico;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
